name: Deploy to Neocities

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload site to Neocities
        run: |
          # Upload all files in repo root recursively
          find . -type f ! -path "./.github/*" -exec curl -F "file=@{}" \
            -H "Authorization: Bearer ${{ secrets.NEOCITIES_API_KEY }}" \
            https://neocities.org/api/upload \;